### ISSUE TITLE
Heroes Api images

### ISSUE THREAD

**Issue by nmarch213** [hotsapi/hotsapi#74]
Hey, I couldn't find a better place to put this. The following heroes do not have an "icon_url" in your database. 

Would you mind updating these: The Butcher, Junkrat and Zul'jin.

http://s3.hotsapi.net/img/heroes/92x93/junkrat.png
http://s3.hotsapi.net/img/heroes/92x93/zuljin.png
http://s3.hotsapi.net/img/heroes/92x93/thebutcher.png

Thanks for all your work!

**Comment by Cruglk** [comment]
Hi! 

Links (need to change for 92x93): 
http://media.blizzard.com/heroes/zuljin/skins/thumbnails/warlord-of-the-amani.jpg
http://media.blizzard.com/heroes/the-butcher/skins/thumbnails/flesh-carver.jpg
http://media.blizzard.com/heroes/junkrat/skins/thumbnails/junker-demolitionist.jpg

**Comment by poma** [comment]
I need to setup automatic image pulling from https://github.com/heroespatchnotes/heroes-talents, they have all hero and talent images.

**Comment by r-t-a** [comment]
The Butcher is actually there, just under "butcher.png" instead of "thebutcher.png"

Also missing,
http://s3.hotsapi.net/img/heroes/92x93/maiev.png
http://s3.hotsapi.net/img/heroes/92x93/blaze.png
http://s3.hotsapi.net/img/heroes/92x93/alexstraza.png

Thanks!

**Comment by MGatner** [comment]
Is there any advantage to pulling images rather than just linking to other sources? E.g. `heroes-talents`:
*  https://github.com/heroespatchnotes/heroes-talents/raw/master/images/heroes/zuljin.png

Or the uncompressed version from Heroes Tool Chest:
* https://github.com/HeroesToolChest/heroes-images/raw/master/heroesimages/heroportraits/ui_targetportrait_hero_zuljin.png

GitHub assets shouldn't be used as CDN but I imagine HotsApi would appreciate the same so we could just update the URL and continue to request that people download instead of source tag.

**Comment by poma** [comment]
My intention was to provide a CDN for common images, but if linking to github works it's even better

**Comment by whoshallsucceed** [comment]
@MGatner Are you sure it's fixed? I keep getting `https://hotsapi.net/api/v1/heroes/...` URLs from https://hotsapi.net/api/v1/heroes
